[package]
name = "mandlebrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8"
num = "0.4"
image = "0.13.0"
structopt = "0.3"